# Generated by Django 2.2.10 on 2021-07-09 21:59

from django.db import migrations, models
import team_tool.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csvFile', models.FileField(upload_to='', validators=[team_tool.validators.validate_file_extension])),
            ],
        ),
    ]
