# Generated by Django 2.2.10 on 2021-07-09 22:07

from django.db import migrations, models
import team_tool.validators


class Migration(migrations.Migration):

    dependencies = [
        ('team_tool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='csvFile',
            field=models.FileField(upload_to='surveys/csv/', validators=[team_tool.validators.validate_file_extension]),
        ),
    ]
