# Generated by Django 2.2.10 on 2021-07-10 23:36

from django.db import migrations, models
import teamFormation.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teamFormation', '0003_auto_20210706_2348'),
    ]

    operations = [
        migrations.CreateModel(
            name='csvUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csvFile', models.FileField(upload_to='surveys/csv/', validators=[teamFormation.validators.validate_file_extension])),
            ],
        ),
        migrations.CreateModel(
            name='pickCols',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='teamSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
