# Generated by Django 3.2.5 on 2021-07-14 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamFormation', '0008_auto_20210710_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvupload',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pickcols',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='teamsize',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
